baseURL = "https://focused-mcnulty-b07f4d.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[[menu.main]]
 name = "Home"
 url = "https://focused-mcnulty-b07f4d.netlify.app/"
 weight = 1
    
[[menu.main]]
 name = "All Posts"
 url = "https://focused-mcnulty-b07f4d.netlify.app/posts/"
 weight = 2

[[menu.main]]
 name = "Music"
 url = "/content/music.md/"
 weight = 3

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

